### ISSUE TITLE
Rx : fromAsync has been removed in newer version

### ISSUE THREAD

**Issue by lucas34** [airbnb/RxGroups#28]
Hi,

The method fromAsync() as been removed in Rx version 1.2.0. It has been replaced by fromEmitter.
However, They are still in discussion about the signature and the interface name.

Even if we replace now the fromAsync with the fromEmitter, I'm scare we need to do it again for the next Rx release. I think we should avoid using the experimental operator in libraries.

Feel free to late me know what do you think. 
I can make a PR.

Lucas.

**Comment by felipecsl** [comment]
@lucas34 agreed this is not ideal, but doesn't seem like RxJava has any other operator/construct that works similarly. I don't want to go back to `create()` since it has many pitfalls.
I think that as long as we bump the lib major version with every change, it's OK to make breaking changes.
I'd be happy to merge a PR that replaces it with `fromEmitter` and cut a `1.0.0` release
